apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
    path('',views.list_accounts, name='list_accounts'),
    path('editar/<int:id_account>/', views.edit_account, name='edit_account'),
    path('buscar/', views.search_accounts, name='search_accounts'),       
]

apps/annotations/urls.py
from django.urls import path
from . import views

app_name = 'annotations'

urlpatterns = [
    path('', views.list_annotations, name='list_annotations'),
    path('admin/<int:id_account>/', views.list_annotations_admin, name='list_annotations_admin'),    
    path('adicionar/', views.add_annotation, name='add_annotation'),
    path('editar/<int:id_annotation>/', views.edit_annotation, name='edit_annotation'),
    path('admin/<int:id_annotation>/comentario/', views.add_annotation_comment, name='add_annotation_comment'),
    path('admin/<int:id_annotation>/comentario/editar', views.add_annotation_comment, name='edit_annotation_comment'),
    path('relatorio-alertas/', views.report_alerts, name='report_alerts'),
    path('relatorio-emocional/', views.report_emotional_trends, name='report_emotional_trends'),    
]

apps/prescriptions/urls.py
from django.urls import path
from . import views

app_name = 'prescriptions'

urlpatterns = [
    path('', views.list_prescriptions, name='list_prescriptions'),
     path('admin/<int:id_account>/', views.list_prescriptions_admin, name='list_prescriptions_admin'), 
    path('adicionar/', views.add_prescription, name='add_prescription'),
    path('editar/<int:id_prescription>/', views.edit_prescription, name='edit_prescription'),
    path('excluir/<int:id_prescription>/', views.delete_prescription, name='delete_prescription'),
]

bemestarplusapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('anotacoes/', include('annotations.urls', namespace='annotations')),
    path('prescricoes/', include('prescriptions.urls', namespace='prescriptions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models

# Create your models here.

apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password' , 'email']

class UserChangeInformationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email'] #fields = ['first_name', 'last_name', 'email']

class UserFormEdit(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']
        

apps/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from .forms import UserForm, UserChangeInformationForm, UserFormEdit
from annotations.models import Annotations

# Create your views here.

def user_login(request):
    template_name = 'accounts/user_login.html'
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET.get('next', 'annotations:list_annotations'))
            #return redirect(request.GET.get('next', '/'))
        else:
            return redirect('accounts:user_login')
    return render(request, template_name, {})

@login_required(login_url='/contas/login/')
def add_user(request):
    template_name = 'accounts/add_user.html'
    context = {}
    if request.method =='POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.set_password(f.password)
            f.save()
            return redirect('accounts:list_accounts')
        else:
            return redirect('accounts:add_user')
    form = UserForm()
    context['form'] = form
    return render(request, template_name, context) 

@login_required(login_url='/contas/login/')
def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')

@login_required(login_url='/contas/login/')
def user_change_password(request):
    template_name = 'accounts/user_change_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
        else:
            return redirect('accounts:user_login')
    form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def user_change_information(request, username):
    template_name = 'accounts/user_change_information.html'
    context = {}
    user = User.objects.get(username=username)
    if request.method == 'POST':
        form = UserChangeInformationForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
    form = UserChangeInformationForm(instance=user)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_accounts(request):
    template_name = 'accounts/list_accounts.html'
    account = User.objects.order_by('id').all()  # Recupera todos os usuários
    #annotation = Annotations.objects.all()  # Recupera todos os usuários
    context = {
        'accounts': account,
        #'annotations': annotation,
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def search_accounts(request):    
    template_name = 'accounts/list_accounts.html'
    query = request.GET.get('query')     
    account = User.objects.filter(first_name__icontains=query)
    annotation = Annotations.objects.all()
    context = {
        'accounts': account,
        'annotations': annotation,
    }
    return render(request,template_name, context)

@login_required(login_url='/contas/login/')
def edit_account(request, id_account):
    template_name = 'accounts/add_user.html'
    context ={}
    account = get_object_or_404(User, id=id_account)
    if request.method == 'POST':
        form = UserFormEdit(request.POST, instance=account)
        if form.is_valid():
            form.save()
            return redirect('accounts:list_accounts')
    form = UserFormEdit(instance=account)
    context['form'] = form
    return render(request, template_name, context)

templates/accounts/add_user.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Novo usuario - {{ block.super}}
{% endblock title %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12">
            <h1>Novo usuario</h1>
                <form action="" method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.first_name.id_for_label }}">Nome</label>
                        {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                        {{ form.last_name|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.username.id_for_label }}">Nome de usuario</label>
                        {{ form.username|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">E-mail</label>
                        {{ form.email|add_class:"form-control" }}
                    </div>
                    {% if form.password is not null %}
                    <div class="form-group">
                        <label for="{{ form.password.id_for_label }}">Senha</label>
                        {{ form.password|add_class:"form-control"|attr:"type:password" }}
                    </div>
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/accounts/list_accounts.html
{% extends 'base.html' %}

{% block title %}

    Lista de Pacientes - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
    {% if user.is_superuser %}
        <br />
        <h5><b>Lista de Pacientes</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'accounts:add_user' %}">Adicionar novo Paciente</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Sobrenome</th>
                    <th scope="col">E-mail</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for account in accounts %}                    
                        <tr>
                            <th scope="row">{{ account.id }}</th>
                            <td>{{ account.first_name }}</td>
                            <td>{{ account.last_name }}</td>
                            <td>{{ account.email }}</td>
                            <td>
                                <a href="{% url 'accounts:edit_account' account.id %}" class="btn btn-primary btn-sm">Editar</a>                                
                            </td>
                            <td>
                                <a href="{% url 'annotations:list_annotations_admin' account.id %}" class="btn btn-primary btn-sm">Acompanhar Paciente</a>                                
                            </td>
                            <td>
                                <a href="{% url 'prescriptions:list_prescriptions_admin' account.id %}" class="btn btn-primary btn-sm">Prescrições</a>                                
                            </td>    
                        </tr>                     
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <br />
        <br />
        <h5><b>Você não tem Permissão.</b></h5>
    {% endif %}
    </div>

{% endblock body %}

templates/accounts/user_change_information.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    Novo usuario - {{ block.super}}
{% endblock title %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-12">
            <h1>Alterar usuario</h1>
                <form action="" method="POST">
                {% csrf_token %}
                    <!--
                    <div class="form-group">
                        <label for="{{ form.first_name.id_for_label }}">Primerio nome</label>
                        {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                        {{ form.last_name|add_class:"form-control" }}
                    </div>
                    -->
                    <div class="form-group">
                        <label for="{{ form.email.id_for_label }}">E-mail</label>
                        {{ form.email|add_class:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/accounts/user_change_password.html
{% extends 'base.html' %}

{% load widget_tweaks %}


{% block title %}
    Trocar senha - {{ block.super}}
{% endblock title %}
    

{% block body %}
    
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Alterar Senha</h1>
                <form action="" method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.old_password.id_for_label }}">Senha anterior</label>
                        {{ form.old_password|add_class:"form-control"|attr:"type:password" }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.new_password1.id_for_label }}">Nova senha</label>
                        {{ form.new_password1|add_class:"form-control"|attr:"type:password" }}
                    <div class="form-group">
                        <label for="{{ form.new_password2.id_for_label }}">Confirmar nova senha</label>
                        {{ form.new_password2|add_class:"form-control"|attr:"type:password" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </form>
            </div>
        </div>
    </div>
    
{% endblock body %}

templates/accounts/user_login.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ReviewApp login</title>
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
  <link rel="stylesheet" href="{% static 'css/signin.css' %}" >
</head>
<body class="text-center">

  <form class="form-signin" action="" method="POST">
  {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Identifique-se</h1>
    <label for="username" class="sr-only">Usuario</label>
    <input type="text" id="username" name="username" class="form-control" placeholder="Nome de usuario" required autofocus>
    <label for="password" class="sr-only">Senha</label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Digite sua senha" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
    <br />
    <!--<a href="{% url 'accounts:add_user' %}">Criar uma conta</a>--><!--porque somente pscicolo pode criar novos usuarios -->
  </form>

  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>