apps/prescriptions/urls.py
from django.urls import path
from . import views

app_name = 'prescriptions'

urlpatterns = [
    path('', views.list_prescriptions, name='list_prescriptions'),
     path('admin/<int:id_account>/', views.list_prescriptions_admin, name='list_prescriptions_admin'), 
    path('adicionar/', views.add_prescription, name='add_prescription'),
    path('editar/<int:id_prescription>/', views.edit_prescription, name='edit_prescription'),
    path('excluir/<int:id_prescription>/', views.delete_prescription, name='delete_prescription'),
]

bemestarplusapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('anotacoes/', include('annotations.urls', namespace='annotations')),
    path('prescricoes/', include('prescriptions.urls', namespace='prescriptions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/prescriptions/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Prescription(models.Model):
    diagnoses = models.TextField('Diagnostico', max_length=250)
    prescription = models.TextField('Prescicao de medicamento', max_length=200)
    is_active = models.BooleanField('Status', default=False)
    date_prescription = models.DateField('Data da prescricao', auto_now=False, auto_now_add=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    class Meta:
        verbose_name = 'Prescricao'
        verbose_name_plural = 'Prescricao'
        ordering =['id']

    def __str__(self):
        return self.diagnoses

apps/prescriptions/forms.py
from django import forms
from .models import Prescription

class PrescriptionForm(forms.ModelForm):

    class Meta:
        model = Prescription
        exclude = ('user',)

apps/prescriptions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PrescriptionForm
from .models import Prescription
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/contas/login/')
def add_prescription(request):
    template_name = 'prescriptions/add_prescription.html'
    context = {}
    if request.method == 'POST':
        form = PrescriptionForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            form.save_m2m()
            return redirect('prescriptions:list_prescriptions')
    form = PrescriptionForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_prescriptions(request):
    template_name = 'prescriptions/list_prescriptions.html'
    prescriptions = Prescription.objects.filter(user=request.user)
    context = {
        'prescriptions': prescriptions
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_prescription(request, id_prescription):
    template_name = 'prescriptions/add_prescription.html'
    context ={}
    prescription = get_object_or_404(Prescription, id=id_prescription, user=request.user)
    if request.method == 'POST':
        form = PrescriptionForm(request.POST, instance=prescription)
        if form.is_valid():
            form.save()
            return redirect('prescriptions:list_prescriptions')
    form = PrescriptionForm(instance=prescription)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_prescription(request, id_prescription):
    prescription = Prescription.objects.get(id=id_prescription)
    if prescription.user == request.user:
        prescription.delete()
    else:
        return redirect('core:home')
    return redirect('prescriptions:list_prescriptions')

@login_required(login_url='/contas/login/')
def list_prescriptions_admin(request, id_account):
    template_name = 'prescriptions/list_prescriptions.html'
    prescriptions = Prescription.objects.filter(user_id=id_account)
    context = {
        'prescriptions': prescriptions
    }
    return render(request, template_name, context)

templates/prescriptions/add_prescription.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Prescrição - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Prescrições</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.diagnoses.id_for_label }}">Diagnostico</label>
                   {{ form.diagnoses|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.prescription.id_for_label }}">Prescicao de medicamento</label>
                    {{ form.prescription|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.date_prescription.id_for_label }}">Data da prescricao</label>
                    {{ form.date_prescription|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.is_active.id_for_label }}">Ativo</label>
                    {{ form.is_active }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/prescriptions/list_prescriptions.html
{% extends 'base.html' %}

{% block title %}

    Lista de Prescrições - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Prescrições</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'prescriptions:add_prescription' %}">Cadastro de nova prescição</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Diagnostico</th>
                    <th scope="col">Prescicao de medicamento</th>
                    <th scope="col">Data da prescricao</th>
                    <th scope="col">Ativo</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for prescription in prescriptions %}
                        <tr>
                            <th scope="row">{{ prescription.id }}</th>
                            <td>{{ prescription.diagnoses }}</td>
                            <td>{{ prescription.prescription }}</td>
                            <td>{{ prescription.date_prescription }}</td>
                            <td>
                                {% if prescription.is_active == True %}
                                    Ativo
                                {% endif %}
                                {% if prescription.is_active == False %}
                                    Inativo
                                {% endif %}
                            </td>
                             {% if not user.is_superuser %}
                            <td>
                                <a href="{% url 'prescriptions:edit_prescription' prescription.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'prescriptions:delete_prescription' prescription.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

    

{% endblock body %}