apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
    path('',views.list_accounts, name='list_accounts'),
    path('editar/<int:id_account>/', views.edit_account, name='edit_account'),
    path('buscar/', views.search_accounts, name='search_accounts'),       
]

apps/annotations/urls.py
from django.urls import path
from . import views

app_name = 'annotations'

urlpatterns = [
    path('', views.list_annotations, name='list_annotations'),
    path('admin/<int:id_account>/', views.list_annotations_admin, name='list_annotations_admin'),    
    path('adicionar/', views.add_annotation, name='add_annotation'),
    path('editar/<int:id_annotation>/', views.edit_annotation, name='edit_annotation'),
    path('admin/<int:id_annotation>/comentario/', views.add_annotation_comment, name='add_annotation_comment'),
    path('admin/<int:id_annotation>/comentario/editar', views.add_annotation_comment, name='edit_annotation_comment'),
    path('relatorio-alertas/', views.report_alerts, name='report_alerts'),
    path('relatorio-emocional/', views.report_emotional_trends, name='report_emotional_trends'),    
]

apps/prescriptions/urls.py
from django.urls import path
from . import views

app_name = 'prescriptions'

urlpatterns = [
    path('', views.list_prescriptions, name='list_prescriptions'),
     path('admin/<int:id_account>/', views.list_prescriptions_admin, name='list_prescriptions_admin'), 
    path('adicionar/', views.add_prescription, name='add_prescription'),
    path('editar/<int:id_prescription>/', views.edit_prescription, name='edit_prescription'),
    path('excluir/<int:id_prescription>/', views.delete_prescription, name='delete_prescription'),
]

bemestarplusapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('anotacoes/', include('annotations.urls', namespace='annotations')),
    path('prescricoes/', include('prescriptions.urls', namespace='prescriptions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Bem Estar+{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Bem Estar+</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        {% if user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'accounts:list_accounts' %}">Pacientes</a>
                        <a class="dropdown-item" href="{% url 'annotations:report_alerts' %}">Alertas</a>
                        <a class="dropdown-item" href="{% url 'annotations:report_emotional_trends' %}">Relatório Tendências</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'annotations:list_annotations' %}">Anotações</a> 
                        <a class="dropdown-item" href="{% url 'prescriptions:list_prescriptions' %}">Prescrições</a>                         
                    </div>
                </li>
            </ul>
            {% if user.is_superuser %}
            <form action="{% url 'accounts:search_accounts' %}" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
                <input class="form-control" name="query" type="text" placeholder="Nome do paciente" aria-label="Buscar" style="margin-right: 10px">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
            {% endif %}
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                    </div>
                </li>
            </ul>
        </div>
        {% endif %}
    </nav>
    {% block body %}
    

    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>